### ISSUE TITLE
 raise NotImplementedError

### ISSUE THREAD

**Issue by hirios** [elektito/ih2torrent#18]
This command:
`python ih2torrent.py --file test.torrent "magnet:?xt=urn:btih:6d1e38aa6d10e62c827102cb5e21f2d5b3f2e090"`

Return this:

```
[2021-11-16 20:32:29,787][INFO] Using node ID: 4927ed92175a89cb0aa5841ae5e3de76c5d6bbf6
[2021-11-16 20:32:29,800][INFO] Using router.bittorrent.com as the bootstrapping node.
[2021-11-16 20:32:29,800][INFO] Resolving: router.bittorrent.com
Exception ignored from cffi callback <function _sock_state_cb at 0x000001D717F92040>:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ih2torrent\venv\lib\site-packages\pycares\__init__.py", line 99, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\Administrator\Desktop\ih2torrent\venv\lib\site-packages\aiodns\__init__.py", line 111, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError:
```

Windows 10
Python 3.9.5
aiodns==3.0.0
bencodepy==0.9.5
cffi==1.15.0
pycares==4.1.2
pycparser==2.21

**Comment by elektito** [comment]
Thanks for reporting the issue. Looks like this is something that only happens on Windows and I don't have access to a Windows machine right now. I've created a branch that _might_ fix this based on what I read online. Can you give it a try and tell me if it makes any difference? https://github.com/elektito/ih2torrent/tree/selector-loop-for-windows

**Comment by eden881** [comment]
I encountered this too. If you use Docker Desktop you can wrap this tool in a container and it'll work because it uses a Linux VM behind the scenes.

Create this `Dockerfile` in the project root:
```
FROM python:3.12
WORKDIR /code
COPY ./ /code
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
CMD ["/bin/bash"]
```
Then navigate to the project in a shell and run:
```shell
docker build -t ih2torrent .
```
It'll create a container image with the tool installed. Then just run the container and the tool:
```shell
docker run -it ih2torrent
python ih2torrent.py <your-args-here>
```

**Comment by eden881** [comment]
> Thanks for reporting the issue. Looks like this is something that only happens on Windows and I don't have access to a Windows machine right now. I've created a branch that _might_ fix this based on what I read online. Can you give it a try and tell me if it makes any difference? https://github.com/elektito/ih2torrent/tree/selector-loop-for-windows

@elektito ~BTW, this indeed solves the issue on Windows natively 😄~

At first it looks like it works, but then I get:
```
task: <Task cancelling name='get-metadata-109.252.155.50-10287' coro=<get_metadata_with_retries() running at C:\Temp\ih2torrent\ih2torrent.py:564> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback() at C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\tasks.py:767]>
Task was destroyed but it is pending!
task: <Task cancelling name='get-metadata-143.44.196.48-14989' coro=<get_metadata_with_retries() running at C:\Temp\ih2torrent\ih2torrent.py:564> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback() at C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\tasks.py:767]>
Task was destroyed but it is pending!
task: <Task cancelling name='get-metadata-85.64.151.102-1255' coro=<get_metadata_with_retries() running at C:\Temp\ih2torrent\ih2torrent.py:564> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback() at C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\tasks.py:767]>
Task was destroyed but it is pending!

... (many times)

Exception ignored in: <coroutine object get_peers at 0x0000020AC79DE510>
Traceback (most recent call last):
  File "C:\Temp\ih2torrent\ih2torrent.py", line 410, in get_peers
    transport, protocol = await loop.create_datagram_endpoint(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\base_events.py", line 1441, in create_datagram_endpoint
    transport.close()
  File "C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\selector_events.py", line 875, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\base_events.py", line 795, in call_soon
    self._check_closed()
  File "C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object get_peers at 0x0000020AC79DE640>
Traceback (most recent call last):
  File "C:\Temp\ih2torrent\ih2torrent.py", line 410, in get_peers
    transport, protocol = await loop.create_datagram_endpoint(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\base_events.py", line 1441, in create_datagram_endpoint
    transport.close()
  File "C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\selector_events.py", line 875, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\base_events.py", line 795, in call_soon
    self._check_closed()
  File "C:\Users\eden8\.pyenv\pyenv-win\versions\3.12.5\Lib\asyncio\base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

... (many times)
```
